backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "site_feed"
    label: "Gerenciar Site"
    files:
      - file: "conteudo.json" 
        label: "Publicações do Site"
        name: "publicacoes"
        fields:
          - name: posts
            label: "Lista de Itens"
            widget: list
            fields:
              - { label: "Título", name: "title", widget: "string" }
              
              # 🌟 Suas três páginas configuradas aqui:
              - label: "Enviar para qual página?"
                name: "pagina"
                widget: "select"
                options:
                  - { label: "Home", value: "home" }
                  - { label: "Pesquisa", value: "pesquisa" }
                  - { label: "Processos", value: "processos" }
              
              - { label: "Escolher Foto", name: "foto", widget: "image", required: false }
              - { label: "Texto / Descrição", name: "body", widget: "markdown" }
