backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "conteudo"
    label: "Conteúdo do Site"
    files:
      - file: "diario.json" # O CMS vai criar e alimentar este arquivo sozinho
        label: "Meu Diário"
        name: "diario"
        fields:
          - name: posts
            label: "Postagens"
            widget: list # Permite adicionar um post embaixo do outro
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Data", name: "date", widget: "datetime" }
              - { label: "Escolher Foto", name: "foto", widget: "image", required: false }
              - { label: "Texto", name: "body", widget: "markdown" }
